services:
  web:
    build: .
    container_name: barangay_ims_web
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      DJANGO_DB_ENGINE: "django.db.backends.sqlite3"
      DJANGO_DB_NAME: "/app/db.sqlite3"
    volumes:
      - .:/app
    restart: unless-stopped
