# Generated by Django 6.0.3 on 2026-07-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='brand_model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('barangay_fund', 'Barangay Fund'), ('development_fund_20', '20% Development Fund'), ('drrm_fund', 'DRRM Fund'), ('donation', 'Donation'), ('other', 'Other')], default='barangay_fund', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('under_repair', 'Under Repair'), ('disposed', 'Disposed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Current location'),
        ),
    ]
