# Generated by Django 6.0.3 on 2026-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_brand_model_asset_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='responsible_role',
            field=models.CharField(blank=True, choices=[('punong_barangay', 'Punong Barangay'), ('barangay_secretary', 'Barangay Secretary'), ('barangay_treasurer', 'Barangay Treasurer'), ('barangay_kagawad', 'Barangay Kagawad'), ('barangay_health_worker', 'Barangay Health Worker'), ('barangay_nutrition_scholar', 'Barangay Nutrition Scholar'), ('drrm_coordinator', 'DRRM Coordinator'), ('sk_chairman', 'SK Chairman'), ('utility_worker', 'Utility Worker'), ('administrative_aide', 'Administrative Aide')], max_length=40),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unserviceable', 'Unserviceable'), ('for_disposal', 'For Disposal')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('barangay_hall', 'Barangay Hall'), ('barangay_office', 'Barangay Office'), ('health_center', 'Health Center'), ('multi_purpose_hall', 'Multi-Purpose Hall'), ('covered_court', 'Covered Court'), ('session_hall', 'Session Hall'), ('drrm_storage', 'DRRM Storage'), ('records_room', 'Records Room'), ('storage_room', 'Storage Room'), ('garage', 'Garage'), ('day_care_center', 'Day Care Center'), ('senior_citizen_center', 'Senior Citizen Center')], default='barangay_hall', max_length=40, verbose_name='Current location'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='condition_on_return',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unserviceable', 'Unserviceable'), ('for_disposal', 'For Disposal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ict_equipment', 'ICT Equipment'), ('office_furniture', 'Office Furniture'), ('office_equipment', 'Office Equipment'), ('medical_equipment', 'Medical Equipment'), ('disaster_equipment', 'Disaster Equipment'), ('safety_equipment', 'Safety Equipment'), ('communication_equipment', 'Communication Equipment'), ('vehicle', 'Vehicle'), ('heavy_equipment', 'Heavy Equipment'), ('tools_and_equipment', 'Tools & Equipment'), ('buildings', 'Buildings'), ('infrastructure', 'Infrastructure'), ('sports_equipment', 'Sports Equipment'), ('electrical_equipment', 'Electrical Equipment')], max_length=50, unique=True),
        ),
    ]
