# Generated by GitHub Copilot on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_precinct_resident_precinct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='barangay',
            field=models.CharField(default='ABGAO', max_length=100),
        ),
    ]