# Generated by GitHub Copilot on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_alter_resident_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='city_municipality',
            field=models.CharField(default='MAASIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='province',
            field=models.CharField(default='SOUTHERN LEYTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='zip_code',
            field=models.CharField(default='6600', max_length=10),
        ),
    ]