# Generated by Django 6.0.3 on 2026-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_backfill_portal_identity_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('no_formal', 'No Formal Education'), ('elementary', 'Elementary'), ('high_school', 'High School'), ('vocational', 'Vocational'), ('college', 'College'), ('post_graduate', 'Post Graduate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('ofw', 'OFW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
