# Generated by Django 6.0.3 on 2026-06-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0018_resident_qr_code_and_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('scanned_qr', 'Scanned QR'), ('visited_today', 'Visited Today')], default='visited_today', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_service_logs', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Resident Service Log',
                'verbose_name_plural': 'Resident Service Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
