# Generated by Django 6.0.3 on 2026-03-04 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_precinct_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct_number', models.CharField(max_length=20, unique=True)),
                ('precinct_name', models.CharField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, help_text='Physical location/address of the precinct')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum number of registered voters')),
                ('precinct_chairman', models.CharField(blank=True, max_length=150)),
                ('poll_clerk', models.CharField(blank=True, max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precinct',
                'verbose_name_plural': 'Precincts',
                'ordering': ['precinct_number'],
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='precinct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='residents.precinct'),
        ),
    ]
