# Generated by GitHub Copilot on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_resident_address_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='citizenship',
            field=models.CharField(default='FILIPINO', max_length=50),
        ),
    ]