# Generated by Django 6.0.3 on 2026-06-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_alter_resident_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='zone',
            field=models.CharField(choices=[('Purok Talisay', 'Purok Talisay'), ('Purok Malunggay', 'Purok Malunggay'), ('Purok Mancinitas', 'Purok Mancinitas'), ('Purok Narra', 'Purok Narra'), ('Purok Kulo', 'Purok Kulo'), ('Purok Ipil-ipil', 'Purok Ipil-ipil'), ('Purok Tugas', 'Purok Tugas')], max_length=50),
        ),
    ]
