# Generated by Django 6.0.3 on 2026-06-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_alter_resident_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayofficeprofile',
            name='barangay',
            field=models.CharField(default='ABGAO', max_length=100),
        ),
        migrations.AddField(
            model_name='barangayofficeprofile',
            name='city_municipality',
            field=models.CharField(default='MAASIN', max_length=100),
        ),
        migrations.AddField(
            model_name='barangayofficeprofile',
            name='province',
            field=models.CharField(default='SOUTHERN LEYTE', max_length=100),
        ),
    ]
