# Generated by Django 6.0.3 on 2026-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0014_alter_resident_educational_attainment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
