# Generated by Django 6.0.3 on 2026-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0015_alter_resident_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='barangay',
            field=models.CharField(blank=True, default='ABGAO', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='citizenship',
            field=models.CharField(blank=True, default='FILIPINO', max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='city_municipality',
            field=models.CharField(blank=True, default='MAASIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='resident',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='resident',
            name='place_of_birth',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='province',
            field=models.CharField(blank=True, default='SOUTHERN LEYTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='zip_code',
            field=models.CharField(blank=True, default='6600', max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='zone',
            field=models.CharField(blank=True, choices=[('Purok Talisay', 'Purok Talisay'), ('Purok Malunggay', 'Purok Malunggay'), ('Purok Mancinitas', 'Purok Mancinitas'), ('Purok Narra', 'Purok Narra'), ('Purok Kulo', 'Purok Kulo'), ('Purok Ipil-ipil', 'Purok Ipil-ipil'), ('Purok Tugas', 'Purok Tugas')], default='Purok Talisay', max_length=50),
        ),
    ]
