# Generated by Django 6.0.3 on 2026-06-12

import uuid
from django.db import migrations, models


def backfill_resident_qr_codes(apps, schema_editor):
    Resident = apps.get_model('residents', 'Resident')

    for resident in Resident.objects.filter(models.Q(qr_code__isnull=True) | models.Q(qr_code='')):
        code = uuid.uuid4().hex[:16].upper()
        while Resident.objects.filter(qr_code=code).exists():
            code = uuid.uuid4().hex[:16].upper()
        resident.qr_code = code
        resident.save(update_fields=['qr_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0017_alter_resident_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='qr_code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='qr_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='resident_qr_codes/'),
        ),
        migrations.RunPython(backfill_resident_qr_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resident',
            name='qr_code',
            field=models.CharField(blank=True, editable=False, max_length=16, unique=True),
        ),
    ]
