# Generated by Django 6.0.3 on 2026-08-03 03:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_household_memberships(apps, schema_editor):
    Household = apps.get_model('residents', 'Household')
    HouseholdMembership = apps.get_model('residents', 'HouseholdMembership')

    used_codes = set(Household.objects.exclude(household_number='').values_list('household_number', flat=True))
    generated_numbers = [
        int(code[3:])
        for code in used_codes
        if code.startswith('HH-') and code[3:].isdigit()
    ]
    next_number = max(generated_numbers, default=0) + 1

    # Heads are migrated first so every household starts with one active head.
    for household in Household.objects.select_related('household_head').order_by('pk'):
        if HouseholdMembership.objects.filter(
            resident_id=household.household_head_id,
            status='active',
        ).exists():
            raise RuntimeError(
                f'Resident {household.household_head_id} is the head of more than one household.'
            )
        HouseholdMembership.objects.create(
            household_id=household.pk,
            resident_id=household.household_head_id,
            relationship_to_head='head',
            status='active',
            joined_date=household.created_at.date(),
        )

        changed_fields = []
        if not household.household_number:
            while f'HH-{next_number:06d}' in used_codes:
                next_number += 1
            household.household_number = f'HH-{next_number:06d}'
            used_codes.add(household.household_number)
            next_number += 1
            changed_fields.append('household_number')
        if not household.purok:
            household.purok = household.household_head.zone or ''
            changed_fields.append('purok')
        if not household.complete_address:
            head = household.household_head
            address_parts = [head.house_number or '', head.street or '', head.zone or '']
            locality_parts = [head.barangay or '', head.city_municipality or '', head.province or '', head.zip_code or '']
            household.complete_address = ', '.join(
                part.strip() for part in [' '.join(address_parts).strip(), *locality_parts] if part.strip()
            )
            changed_fields.append('complete_address')
        if changed_fields:
            household.save(update_fields=changed_fields)

    for household in Household.objects.order_by('pk'):
        for resident in household.members.all():
            if resident.pk == household.household_head_id:
                continue
            membership_status = 'active'
            left_date = None
            if HouseholdMembership.objects.filter(resident_id=resident.pk, status='active').exists():
                membership_status = 'transferred'
                left_date = household.created_at.date()
            HouseholdMembership.objects.create(
                household_id=household.pk,
                resident_id=resident.pk,
                relationship_to_head='other_relative',
                status=membership_status,
                joined_date=household.created_at.date(),
                left_date=left_date,
            )


def restore_implicit_members(apps, schema_editor):
    Household = apps.get_model('residents', 'Household')
    HouseholdMembership = apps.get_model('residents', 'HouseholdMembership')
    for household in Household.objects.all():
        resident_ids = HouseholdMembership.objects.filter(household_id=household.pk).values_list(
            'resident_id', flat=True
        )
        household.members.add(*resident_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0019_residentservicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='complete_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='household',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='household',
            name='purok',
            field=models.CharField(blank=True, choices=[('Purok Talisay', 'Purok Talisay'), ('Purok Malunggay', 'Purok Malunggay'), ('Purok Mancinitas', 'Purok Mancinitas'), ('Purok Narra', 'Purok Narra'), ('Purok Kulo', 'Purok Kulo'), ('Purok Ipil-ipil', 'Purok Ipil-ipil'), ('Purok Tugas', 'Purok Tugas')], max_length=50),
        ),
        migrations.AddField(
            model_name='household',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='household',
            name='household_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headed_household', to='residents.resident'),
        ),
        migrations.AlterField(
            model_name='household',
            name='household_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_head', models.CharField(choices=[('head', 'Head'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('child', 'Child'), ('father', 'Father'), ('mother', 'Mother'), ('parent', 'Parent'), ('brother', 'Brother'), ('sister', 'Sister'), ('sibling', 'Sibling'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('guardian', 'Guardian'), ('ward', 'Ward'), ('other_relative', 'Other relative'), ('non_relative', 'Non-relative')], default='other_relative', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.localdate)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='residents.household')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='household_memberships', to='residents.resident')),
            ],
            options={
                'ordering': ['household_id', 'resident__last_name', 'resident__first_name'],
            },
        ),
        migrations.RunPython(migrate_household_memberships, restore_implicit_members),
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='households', through='residents.HouseholdMembership', to='residents.resident'),
        ),
        migrations.AddConstraint(
            model_name='householdmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('resident',), name='unique_active_household_per_resident'),
        ),
        migrations.AddConstraint(
            model_name='householdmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('relationship_to_head', 'head'), ('status', 'active')), fields=('household',), name='unique_active_head_per_household'),
        ),
    ]
