# Generated by Django 6.0.3 on 2026-08-03 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0020_household_complete_address_household_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('guardian', 'Guardian'), ('ward', 'Ward')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_relationships', to=settings.AUTH_USER_MODEL)),
                ('from_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships_from', to='residents.resident')),
                ('to_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships_to', to='residents.resident')),
            ],
            options={
                'ordering': ['from_resident_id', 'relationship_type', 'to_resident__last_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_resident', models.F('to_resident')), _negated=True), name='family_relationship_no_self_link'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('from_resident', 'to_resident'), name='unique_active_family_relationship_pair')],
            },
        ),
    ]
