# Generated by Django 6.0.3 on 2026-08-03 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_phase2_links(apps, schema_editor):
    Resident = apps.get_model('residents', 'Resident')
    DocumentRequest = apps.get_model('residents', 'DocumentRequest')
    ResidentQrIdentity = apps.get_model('residents', 'ResidentQrIdentity')

    portal_residents = {
        resident.portal_user_id: resident.id
        for resident in Resident.objects.exclude(portal_user_id=None)
    }
    for request in DocumentRequest.objects.exclude(submitted_by_id=None):
        resident_id = portal_residents.get(request.submitted_by_id)
        if resident_id:
            request.resident_id = resident_id
            request.request_source = 'portal'
            request.save(update_fields=['resident_id', 'request_source'])

    ResidentQrIdentity.objects.bulk_create([
        ResidentQrIdentity(resident_id=resident.id, identifier=resident.qr_code, status='active')
        for resident in Resident.objects.exclude(qr_code='')
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0021_familyrelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='request_source',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('public', 'Public Form'), ('portal', 'Resident Portal'), ('staff', 'Staff Module'), ('profile', 'Resident Profile')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='residents.resident'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('released', 'Released'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('released', 'Released'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='residents.documentrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidentQrIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('reissued', 'Reissued')], default='active', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_qr_identities', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_identities', to='residents.resident')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_qr_identities', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='residents.residentqridentity')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidentQrAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('issued', 'Issued'), ('verified', 'Verified'), ('failed_verification', 'Failed Verification'), ('reissued', 'Reissued'), ('revoked', 'Revoked'), ('printed', 'Printed')], max_length=30)),
                ('result', models.CharField(blank=True, max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_audit_events', to='residents.resident')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='residents.residentqridentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_phase2_links, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='residentqridentity',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('resident',), name='unique_active_qr_identity_per_resident'),
        ),
    ]
