# Generated by Django 6.0.3 on 2026-08-03 12:04

from django.db import migrations, models


def backfill_inactive_status(apps, schema_editor):
    Resident = apps.get_model('residents', 'Resident')
    Resident.objects.filter(is_active=False).update(residency_status='inactive')


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0023_backfill_qr_issue_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='residency_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.RunPython(backfill_inactive_status, migrations.RunPython.noop),
    ]
